name: bukkit-data
author: yWoxys
version: 1.0.0
main: mc.zyntra.bukkit.BukkitMain
description: Professionally developed Bukkit version administrative system and all rights reserved to Zyntra.
website: zyntrastudios.com